# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('max_score', models.FloatField(default=0.0, verbose_name='Maximum score')),
                ('sales_counter', models.PositiveIntegerField(default=0, verbose_name='purchase count')),
                ('price', models.FloatField(verbose_name='Price')),
                ('upload_date', models.DateField(default=django.utils.timezone.now, verbose_name='Upload date')),
                ('game_description', models.CharField(max_length=25, verbose_name='Game description')),
                ('game_url', models.URLField(default='https://git.niksula.hut.fi/oseppala/wsd2016/blob/master/examples/example_game.html', max_length=255, verbose_name='Game url')),
            ],
            options={
                'verbose_name_plural': 'Games',
                'verbose_name': 'Game',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='score')),
                ('items', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'States',
                'verbose_name': 'State',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=25, verbose_name='pid')),
                ('is_success', models.BooleanField(default=False, verbose_name='Transaction complete')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecenter.Game', verbose_name='game')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'verbose_name': 'Transaction',
            },
        ),
    ]
