# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AddField(
            model_name='state',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gamecenter.Game', verbose_name='Game'),
        ),
        migrations.AddField(
            model_name='state',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_reverse_lookup', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reverse_lookup', to=settings.AUTH_USER_MODEL, verbose_name='Developer'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('player', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('player', 'game')]),
        ),
    ]
