# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecenter', '0003_state_purchase_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([]),
        ),
    ]
