# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamecenter', '0004_auto_20170314_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecenter.Game', verbose_name='Game'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('player', 'game')]),
        ),
    ]
